[build]
  # Build command for your React app
  command = "npm run build"

  # Directory where the built files will be located
  publish = "dist"

[build.environment]
  # Node.js version to use
  NODE_VERSION = "18"
  # Ensure we're using Node.js, not Python
  NODE_ENV = "production"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Prevent Netlify from trying to detect Python
[build.ignore]
  command = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!node_modules'"
